// ===== トレーニング種目データベース =====
// PG式 v2.0 カロリー計算のための科学的パラメータを含む
// Total Calories = A + B + C + D 構造
// A: 種目基礎代謝率（間接熱量測定法データ）
// B: 身体組成補正
// C: インターバル代謝コスト
// D: EPOC（非線形モデル）

const trainingDatabase = {
    "胸": {
        "バーベルベンチプレス": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 3.0,
            baselineRate: 11.41, // 間接熱量測定法データ（80% 1RM）
            lbmMetabolicRate: 22,
            fatMetabolicRate: 4.5,
            epocBaseRate: 0.06,
            epocIntensityFactor: 0.15,
            intervalMultiplier: 1.3,
            concentricWeight: 1.0,
            eccentricWeight: 0.4,
            isometricWeight: 0.8,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部", "上腕三頭筋"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "プッシュ",
            description: "胸トレーニングの王道。上半身のプッシュ力を総合的に鍛える多関節種目"
        },
        "ダンベルベンチプレス": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 3.0,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部", "上腕三頭筋"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "プッシュ",
            description: "可動域が広く、左右独立して鍛えられるベンチプレス"
        },
        "インクラインベンチプレス": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 3.0,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大胸筋上部"],
            secondaryMuscles: ["三角筋前部", "上腕三頭筋"],
            equipment: "バーベル/ダンベル",
            difficulty: "中級",
            movement: "プッシュ",
            description: "30-45度の角度で大胸筋上部を重点的に刺激"
        },
        "ダンベルフライ": {
            category: "胸",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.6,
            defaultTutPerRep: 3.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "フライ",
            description: "大胸筋のストレッチと収縮を重視した単関節種目"
        },
        "ケーブルクロスオーバー": {
            category: "胸",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.7,
            defaultTutPerRep: 3.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部"],
            equipment: "ケーブルマシン",
            difficulty: "初級",
            movement: "フライ",
            description: "ケーブルによる一定の張力で大胸筋を収縮させる"
        },
        "ディップス": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.17,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大胸筋下部", "上腕三頭筋"],
            secondaryMuscles: ["三角筋前部"],
            equipment: "ディップスバー",
            difficulty: "中級",
            movement: "プッシュ",
            description: "自重による高強度プッシュ種目。前傾で胸、直立で三頭筋を強調"
        },
        "プッシュアップ": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部", "上腕三頭筋", "体幹"],
            equipment: "自重",
            difficulty: "初級",
            movement: "プッシュ",
            description: "基本的な自重プッシュ種目。様々なバリエーションが可能"
        },
        "マシンチェストプレス": {
            category: "胸",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大胸筋"],
            secondaryMuscles: ["三角筋前部", "上腕三頭筋"],
            equipment: "マシン",
            difficulty: "初級",
            movement: "プッシュ",
            description: "マシンガイドによる安定した軌道で大胸筋を鍛える"
        }
    },
    "背中": {
        "デッドリフト": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.4,
            defaultTutPerRep: 3.5,
            exerciseFactor: 2.8,
            epocRate: 0.20,
            intervalMultiplier: 1.5,
            primaryMuscles: ["脊柱起立筋", "広背筋", "僧帽筋", "大臀筋", "ハムストリングス"],
            secondaryMuscles: ["前腕", "大腿四頭筋", "体幹"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "ヒンジ",
            description: "全身を使う最高強度の種目。背面チェーン全体を強化"
        },
        "懸垂（プルアップ）": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 3.0,
            exerciseFactor: 1.5,
            epocRate: 0.17,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋"],
            secondaryMuscles: ["僧帽筋", "上腕二頭筋", "三角筋後部"],
            equipment: "懸垂バー",
            difficulty: "上級",
            movement: "プル",
            description: "自重で行う高強度プル種目。背中の幅と厚みを同時に鍛える"
        },
        "ラットプルダウン": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.6,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋"],
            secondaryMuscles: ["僧帽筋", "上腕二頭筋", "三角筋後部"],
            equipment: "ケーブルマシン",
            difficulty: "初級",
            movement: "プル",
            description: "懸垂の代替種目。重量調整が容易で初心者にも安全"
        },
        "ベントオーバーロウ": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋", "僧帽筋"],
            secondaryMuscles: ["脊柱起立筋", "上腕二頭筋", "三角筋後部"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "プル",
            description: "前傾姿勢で背中の厚みを作る基本ロウ種目"
        },
        "ワンハンドダンベルロウ": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋"],
            secondaryMuscles: ["僧帽筋", "上腕二頭筋", "三角筋後部"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "プル",
            description: "片側ずつ行うロウ種目。可動域が広く左右独立して鍛えられる"
        },
        "シーテッドロウ": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.6,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋", "僧帽筋"],
            secondaryMuscles: ["上腕二頭筋", "三角筋後部"],
            equipment: "ケーブルマシン",
            difficulty: "初級",
            movement: "プル",
            description: "座位で行うロウ種目。安定した姿勢で背中の厚みを鍛える"
        },
        "Tバーロウ": {
            category: "背中",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["広背筋", "僧帽筋"],
            secondaryMuscles: ["脊柱起立筋", "上腕二頭筋"],
            equipment: "Tバー",
            difficulty: "中級",
            movement: "プル",
            description: "バーベルの一端を固定して行うロウ種目。高重量を扱いやすい"
        }
    },
    "脚": {
        "バーベルスクワット": {
            category: "脚",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.4,
            defaultTutPerRep: 3.5,
            exerciseFactor: 2.2,
            epocRate: 0.18,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大腿四頭筋", "大臀筋", "ハムストリングス"],
            secondaryMuscles: ["体幹", "脊柱起立筋", "カーフ"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "スクワット",
            description: "下半身トレーニングの王道。脚全体と体幹を総合的に鍛える"
        },
        "フロントスクワット": {
            category: "脚",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.4,
            defaultTutPerRep: 3.5,
            exerciseFactor: 2.2,
            epocRate: 0.18,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大腿四頭筋"],
            secondaryMuscles: ["大臀筋", "体幹", "脊柱起立筋"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "スクワット",
            description: "バーを前に担ぐスクワット。大腿四頭筋と体幹を強化"
        },
        "ブルガリアンスクワット": {
            category: "脚",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.3,
            defaultTutPerRep: 3.0,
            exerciseFactor: 2.2,
            epocRate: 0.17,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大腿四頭筋", "大臀筋"],
            secondaryMuscles: ["ハムストリングス", "体幹"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "スクワット",
            description: "片脚を後ろに上げて行うスクワット。高強度で片側ずつ鍛える"
        },
        "レッグプレス": {
            category: "脚",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.5,
            defaultTutPerRep: 3.0,
            exerciseFactor: 2.2,
            epocRate: 0.17,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大腿四頭筋", "大臀筋", "ハムストリングス"],
            secondaryMuscles: ["カーフ"],
            equipment: "マシン",
            difficulty: "初級",
            movement: "プレス",
            description: "マシンで安全に高重量を扱える脚全体の種目"
        },
        "レッグエクステンション": {
            category: "脚",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["大腿四頭筋"],
            secondaryMuscles: [],
            equipment: "マシン",
            difficulty: "初級",
            movement: "エクステンション",
            description: "大腿四頭筋を単独で鍛える単関節種目"
        },
        "レッグカール": {
            category: "脚",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["ハムストリングス"],
            secondaryMuscles: ["カーフ"],
            equipment: "マシン",
            difficulty: "初級",
            movement: "カール",
            description: "ハムストリングスを単独で鍛える単関節種目"
        },
        "ルーマニアンデッドリフト": {
            category: "脚",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.4,
            defaultTutPerRep: 3.0,
            exerciseFactor: 2.2,
            epocRate: 0.18,
            intervalMultiplier: 1.4,
            primaryMuscles: ["ハムストリングス", "大臀筋"],
            secondaryMuscles: ["脊柱起立筋", "前腕"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "ヒンジ",
            description: "膝を少し曲げてハムストリングスと臀筋を強調したデッドリフト"
        },
        "カーフレイズ": {
            category: "脚",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.15,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["カーフ（腓腹筋・ヒラメ筋）"],
            secondaryMuscles: [],
            equipment: "マシン/ダンベル",
            difficulty: "初級",
            movement: "レイズ",
            description: "ふくらはぎを鍛える単関節種目。立位または座位で実施"
        }
    },
    "肩": {
        "ショルダープレス": {
            category: "肩",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["三角筋"],
            secondaryMuscles: ["上腕三頭筋", "僧帽筋"],
            equipment: "バーベル/ダンベル",
            difficulty: "中級",
            movement: "プレス",
            description: "肩トレーニングの基本種目。三角筋全体を鍛える"
        },
        "ダンベルショルダープレス": {
            category: "肩",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["三角筋"],
            secondaryMuscles: ["上腕三頭筋", "僧帽筋"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "プレス",
            description: "ダンベルで可動域を広く取れるショルダープレス"
        },
        "サイドレイズ": {
            category: "肩",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["三角筋中部"],
            secondaryMuscles: ["僧帽筋"],
            equipment: "ダンベル",
            difficulty: "初級",
            movement: "レイズ",
            description: "三角筋中部を集中的に鍛える単関節種目。肩幅を作る"
        },
        "フロントレイズ": {
            category: "肩",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["三角筋前部"],
            secondaryMuscles: ["大胸筋上部"],
            equipment: "ダンベル/バーベル",
            difficulty: "初級",
            movement: "レイズ",
            description: "三角筋前部を集中的に鍛える単関節種目"
        },
        "リアデルトフライ": {
            category: "肩",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["三角筋後部"],
            secondaryMuscles: ["僧帽筋", "広背筋"],
            equipment: "ダンベル",
            difficulty: "中級",
            movement: "フライ",
            description: "三角筋後部を集中的に鍛える単関節種目。姿勢改善にも効果的"
        },
        "アップライトロウ": {
            category: "肩",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["三角筋", "僧帽筋"],
            secondaryMuscles: ["上腕二頭筋"],
            equipment: "バーベル/ダンベル",
            difficulty: "中級",
            movement: "プル",
            description: "肘を高く上げて三角筋と僧帽筋を鍛える多関節種目"
        },
        "フェイスプル": {
            category: "肩",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.5,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["三角筋後部", "僧帽筋"],
            secondaryMuscles: ["ローテーターカフ"],
            equipment: "ケーブルマシン",
            difficulty: "中級",
            movement: "プル",
            description: "顔に向かって引く動作で肩の健康と姿勢を改善"
        }
    },
    "腕": {
        "バーベルカール": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕二頭筋"],
            secondaryMuscles: ["前腕"],
            equipment: "バーベル",
            difficulty: "初級",
            movement: "カール",
            description: "上腕二頭筋を鍛える基本種目。高重量を扱える"
        },
        "ダンベルカール": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕二頭筋"],
            secondaryMuscles: ["前腕"],
            equipment: "ダンベル",
            difficulty: "初級",
            movement: "カール",
            description: "ダンベルで可動域を広く取れる二頭筋種目"
        },
        "ハンマーカール": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕二頭筋", "上腕筋"],
            secondaryMuscles: ["前腕"],
            equipment: "ダンベル",
            difficulty: "初級",
            movement: "カール",
            description: "手のひらを向かい合わせて行うカール。上腕筋と前腕を強化"
        },
        "トライセプスプッシュダウン": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕三頭筋"],
            secondaryMuscles: [],
            equipment: "ケーブルマシン",
            difficulty: "初級",
            movement: "エクステンション",
            description: "ケーブルで上腕三頭筋を集中的に鍛える単関節種目"
        },
        "スカルクラッシャー": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕三頭筋"],
            secondaryMuscles: [],
            equipment: "バーベル/EZバー",
            difficulty: "中級",
            movement: "エクステンション",
            description: "ライイング状態で額に向かって下ろす三頭筋種目"
        },
        "オーバーヘッドトライセプスエクステンション": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.15,
            intervalMultiplier: 1.2,
            primaryMuscles: ["上腕三頭筋"],
            secondaryMuscles: [],
            equipment: "ダンベル/ケーブル",
            difficulty: "中級",
            movement: "エクステンション",
            description: "頭上でダンベルを下ろして三頭筋の長頭を強調"
        },
        "リストカール": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.15,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["前腕屈筋群"],
            secondaryMuscles: [],
            equipment: "バーベル/ダンベル",
            difficulty: "初級",
            movement: "カール",
            description: "前腕の屈筋群を鍛える単関節種目"
        },
        "リバースリストカール": {
            category: "腕",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.15,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["前腕伸筋群"],
            secondaryMuscles: [],
            equipment: "バーベル/ダンベル",
            difficulty: "初級",
            movement: "エクステンション",
            description: "前腕の伸筋群を鍛える単関節種目"
        }
    },
    "腹筋・体幹": {
        "プランク": {
            category: "腹筋・体幹",
            subcategory: "アイソメトリック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0,
            defaultTutPerRep: 30.0,
            exerciseFactor: 1.5,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹直筋", "腹横筋", "体幹全体"],
            secondaryMuscles: ["大臀筋", "三角筋"],
            equipment: "自重",
            difficulty: "初級",
            movement: "アイソメトリック",
            description: "体幹の安定性を高める基本アイソメトリック種目"
        },
        "クランチ": {
            category: "腹筋・体幹",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.2,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.13,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹直筋"],
            secondaryMuscles: [],
            equipment: "自重",
            difficulty: "初級",
            movement: "屈曲",
            description: "腹直筋を集中的に鍛える基本腹筋種目"
        },
        "レッグレイズ": {
            category: "腹筋・体幹",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.0,
            epocRate: 0.14,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹直筋下部", "腸腰筋"],
            secondaryMuscles: [],
            equipment: "自重",
            difficulty: "中級",
            movement: "屈曲",
            description: "仰向けで脚を上げて腹直筋下部を強調"
        },
        "ハンギングレッグレイズ": {
            category: "腹筋・体幹",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_upper",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["腹直筋下部", "腸腰筋"],
            secondaryMuscles: ["前腕", "広背筋"],
            equipment: "懸垂バー",
            difficulty: "上級",
            movement: "屈曲",
            description: "ぶら下がった状態で脚を上げる高強度腹筋種目"
        },
        "ロシアンツイスト": {
            category: "腹筋・体幹",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.5,
            epocRate: 0.13,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹斜筋", "腹直筋"],
            secondaryMuscles: ["体幹"],
            equipment: "ダンベル/メディシンボール",
            difficulty: "中級",
            movement: "回旋",
            description: "回旋動作で腹斜筋を鍛える種目"
        },
        "バイシクルクランチ": {
            category: "腹筋・体幹",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.5,
            epocRate: 0.14,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹直筋", "腹斜筋"],
            secondaryMuscles: [],
            equipment: "自重",
            difficulty: "中級",
            movement: "屈曲・回旋",
            description: "自転車を漕ぐような動きで腹筋全体を刺激"
        },
        "アブローラー": {
            category: "腹筋・体幹",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.8,
            defaultTutPerRep: 3.0,
            exerciseFactor: 1.5,
            epocRate: 0.16,
            intervalMultiplier: 1.3,
            primaryMuscles: ["腹直筋", "体幹全体"],
            secondaryMuscles: ["広背筋", "三角筋", "上腕三頭筋"],
            equipment: "アブローラー",
            difficulty: "上級",
            movement: "伸展・屈曲",
            description: "ローラーを前後に転がす高強度体幹種目"
        },
        "サイドプランク": {
            category: "腹筋・体幹",
            subcategory: "アイソメトリック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0,
            defaultTutPerRep: 30.0,
            exerciseFactor: 1.5,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹斜筋", "腹横筋"],
            secondaryMuscles: ["中臀筋", "肩"],
            equipment: "自重",
            difficulty: "中級",
            movement: "アイソメトリック",
            description: "横向きプランクで腹斜筋と体幹側面を強化"
        },
        "デッドバグ": {
            category: "腹筋・体幹",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.5,
            exerciseFactor: 1.5,
            epocRate: 0.13,
            intervalMultiplier: 1.2,
            primaryMuscles: ["腹横筋", "体幹"],
            secondaryMuscles: ["腹直筋", "腸腰筋"],
            equipment: "自重",
            difficulty: "初級",
            movement: "交互動作",
            description: "仰向けで対側の腕と脚を伸ばす体幹安定性種目"
        }
    },
    "尻": {
        "ヒップスラスト": {
            category: "尻",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.3,
            defaultTutPerRep: 2.5,
            exerciseFactor: 2.2,
            epocRate: 0.17,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大臀筋"],
            secondaryMuscles: ["ハムストリングス", "体幹"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "伸展",
            description: "臀筋を最も効果的に鍛える種目。背中をベンチに乗せて実施"
        },
        "グルートブリッジ": {
            category: "尻",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.2,
            defaultTutPerRep: 2.0,
            exerciseFactor: 2.2,
            epocRate: 0.15,
            intervalMultiplier: 1.3,
            primaryMuscles: ["大臀筋"],
            secondaryMuscles: ["ハムストリングス", "体幹"],
            equipment: "自重",
            difficulty: "初級",
            movement: "伸展",
            description: "仰向けで腰を上げる基本的な臀筋種目"
        },
        "ケーブルキックバック": {
            category: "尻",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.4,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.14,
            intervalMultiplier: 1.2,
            primaryMuscles: ["大臀筋"],
            secondaryMuscles: ["ハムストリングス"],
            equipment: "ケーブルマシン",
            difficulty: "初級",
            movement: "伸展",
            description: "ケーブルで脚を後ろに蹴り上げて臀筋を集中的に刺激"
        },
        "バンドサイドウォーク": {
            category: "尻",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 5.0,
            defaultTutPerRep: 1.5,
            exerciseFactor: 1.0,
            epocRate: 0.13,
            intervalMultiplier: 1.2,
            primaryMuscles: ["中臀筋", "小臀筋"],
            secondaryMuscles: ["大臀筋"],
            equipment: "レジスタンスバンド",
            difficulty: "初級",
            movement: "外転",
            description: "バンドを膝上に巻いて横歩きで中臀筋を強化"
        },
        "クラムシェル": {
            category: "尻",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.2,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.12,
            intervalMultiplier: 1.2,
            primaryMuscles: ["中臀筋", "小臀筋"],
            secondaryMuscles: [],
            equipment: "レジスタンスバンド",
            difficulty: "初級",
            movement: "外旋",
            description: "横向きで膝を開く動作で中臀筋を活性化"
        },
        "シングルレッググルートブリッジ": {
            category: "尻",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "multi_lower",
            defaultDistance: 0.2,
            defaultTutPerRep: 2.5,
            exerciseFactor: 2.2,
            epocRate: 0.16,
            intervalMultiplier: 1.4,
            primaryMuscles: ["大臀筋"],
            secondaryMuscles: ["ハムストリングス", "体幹"],
            equipment: "自重",
            difficulty: "中級",
            movement: "伸展",
            description: "片脚で行うグルートブリッジ。高強度で片側ずつ鍛える"
        },
        "スモウデッドリフト": {
            category: "尻",
            subcategory: "コンパウンド",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.4,
            defaultTutPerRep: 3.5,
            exerciseFactor: 2.8,
            epocRate: 0.19,
            intervalMultiplier: 1.5,
            primaryMuscles: ["大臀筋", "内転筋群", "ハムストリングス"],
            secondaryMuscles: ["脊柱起立筋", "広背筋", "前腕"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "ヒンジ",
            description: "ワイドスタンスで大臀筋と内転筋を強調したデッドリフト"
        },
        "フロッグパンプ": {
            category: "尻",
            subcategory: "アイソレーション",
            exerciseType: "anaerobic",
            jointType: "single",
            defaultDistance: 0.2,
            defaultTutPerRep: 2.0,
            exerciseFactor: 1.0,
            epocRate: 0.13,
            intervalMultiplier: 1.2,
            primaryMuscles: ["大臀筋"],
            secondaryMuscles: [],
            equipment: "自重",
            difficulty: "初級",
            movement: "伸展",
            description: "足裏を合わせた状態で腰を上げて臀筋を収縮させる"
        }
    },
    "オリンピックリフティング": {
        "スナッチ": {
            category: "オリンピックリフティング",
            subcategory: "オリンピック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 1.0,
            defaultTutPerRep: 1.5,
            exerciseFactor: 2.8,
            epocRate: 0.20,
            intervalMultiplier: 1.5,
            primaryMuscles: ["全身"],
            secondaryMuscles: ["体幹", "肩", "脚", "背中"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "爆発的伸展",
            description: "バーベルを一気に頭上まで引き上げる最高難度の全身種目。パワー・スピード・技術が必要"
        },
        "クリーン&ジャーク": {
            category: "オリンピックリフティング",
            subcategory: "オリンピック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 1.2,
            defaultTutPerRep: 2.0,
            exerciseFactor: 2.8,
            epocRate: 0.20,
            intervalMultiplier: 1.5,
            primaryMuscles: ["全身"],
            secondaryMuscles: ["脚", "背中", "肩", "体幹"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "爆発的伸展",
            description: "バーベルを肩まで引き上げ、さらに頭上に押し上げる2段階の全身種目"
        },
        "パワークリーン": {
            category: "オリンピックリフティング",
            subcategory: "オリンピック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 1.0,
            defaultTutPerRep: 1.5,
            exerciseFactor: 2.8,
            epocRate: 0.19,
            intervalMultiplier: 1.5,
            primaryMuscles: ["脚", "背中", "肩"],
            secondaryMuscles: ["僧帽筋", "体幹", "前腕"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "爆発的伸展",
            description: "床からバーベルを肩まで爆発的に引き上げる。パワーとスピードを養成"
        },
        "ハングクリーン": {
            category: "オリンピックリフティング",
            subcategory: "オリンピック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.8,
            defaultTutPerRep: 1.5,
            exerciseFactor: 2.8,
            epocRate: 0.18,
            intervalMultiplier: 1.5,
            primaryMuscles: ["脚", "背中", "肩"],
            secondaryMuscles: ["僧帽筋", "体幹"],
            equipment: "バーベル",
            difficulty: "上級",
            movement: "爆発的伸展",
            description: "膝上からバーベルを肩まで引き上げる。パワークリーンより短い可動域"
        },
        "プッシュプレス": {
            category: "オリンピックリフティング",
            subcategory: "オリンピック",
            exerciseType: "anaerobic",
            jointType: "full_body",
            defaultDistance: 0.6,
            defaultTutPerRep: 2.0,
            exerciseFactor: 2.8,
            epocRate: 0.17,
            intervalMultiplier: 1.4,
            primaryMuscles: ["肩", "脚"],
            secondaryMuscles: ["上腕三頭筋", "体幹"],
            equipment: "バーベル",
            difficulty: "中級",
            movement: "爆発的プレス",
            description: "脚の反動を使ってバーベルを頭上に押し上げる爆発的種目"
        }
    },
    "有酸素運動": {
        "ランニング": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 5000,
            defaultTutPerRep: 1800,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["下半身全体", "心肺機能"],
            secondaryMuscles: ["体幹"],
            equipment: "なし",
            difficulty: "初級",
            movement: "有酸素",
            description: "基本的な有酸素運動。心肺機能と持久力を向上"
        },
        "サイクリング": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 15000,
            defaultTutPerRep: 1800,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["大腿四頭筋", "ハムストリングス", "カーフ"],
            secondaryMuscles: ["大臀筋", "体幹"],
            equipment: "自転車",
            difficulty: "初級",
            movement: "有酸素",
            description: "関節への負担が少ない有酸素運動。長時間続けやすい"
        },
        "水泳": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 1000,
            defaultTutPerRep: 1200,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["全身", "心肺機能"],
            secondaryMuscles: [],
            equipment: "プール",
            difficulty: "中級",
            movement: "有酸素",
            description: "全身を使う低負荷有酸素運動。関節への負担が最小"
        },
        "ローイングマシン": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 5000,
            defaultTutPerRep: 1200,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["背中", "脚", "心肺機能"],
            secondaryMuscles: ["腕", "体幹"],
            equipment: "ローイングマシン",
            difficulty: "中級",
            movement: "有酸素",
            description: "全身を使う有酸素運動。カロリー消費が高い"
        },
        "エリプティカル": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 5000,
            defaultTutPerRep: 1800,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["下半身全体", "心肺機能"],
            secondaryMuscles: ["体幹"],
            equipment: "エリプティカルマシン",
            difficulty: "初級",
            movement: "有酸素",
            description: "関節への負担が少ない楕円運動の有酸素運動"
        },
        "ステアクライマー": {
            category: "有酸素運動",
            subcategory: "持久系",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 1000,
            defaultTutPerRep: 1200,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["大臀筋", "大腿四頭筋", "ハムストリングス"],
            secondaryMuscles: ["カーフ", "体幹"],
            equipment: "ステアクライマー",
            difficulty: "中級",
            movement: "有酸素",
            description: "階段昇降運動。臀筋と脚に高負荷の有酸素運動"
        },
        "バトルロープ": {
            category: "有酸素運動",
            subcategory: "HIIT",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 0,
            defaultTutPerRep: 300,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["肩", "背中", "腕"],
            secondaryMuscles: ["体幹", "脚"],
            equipment: "バトルロープ",
            difficulty: "中級",
            movement: "HIIT",
            description: "ロープを激しく波打たせる高強度有酸素運動"
        },
        "ボックスジャンプ": {
            category: "有酸素運動",
            subcategory: "HIIT",
            exerciseType: "aerobic",
            jointType: "aerobic",
            defaultDistance: 0.6,
            defaultTutPerRep: 2.0,
            exerciseFactor: null,
            epocRate: null,
            intervalMultiplier: null,
            primaryMuscles: ["大腿四頭筋", "大臀筋", "ハムストリングス"],
            secondaryMuscles: ["カーフ", "体幹"],
            equipment: "プライオボックス",
            difficulty: "中級",
            movement: "プライオメトリック",
            description: "ボックスに飛び乗る爆発的な動作。パワーと瞬発力を養成"
        }
    }
};

// PG式 v2.0デフォルト値の自動補完
// 間接熱量測定法による実測データ（kcal/min at 80% 1RM）
const baselineRateMapping = {
    // 胸
    "バーベルベンチプレス": 11.41,
    "インクラインベンチプレス": 16.77,
    // 背中
    "ラットプルダウン": 9.58,
    "デッドリフト": 28.0, // 推定値（全身種目・高強度）
    // 脚
    "バーベルスクワット": 35.94, // ハーフスクワット実測値
    "レッグプレス": 19.86,
    "レッグエクステンション": 25.70,
    // 腕
    "バーベルカール": 8.53, // バイセップスカール実測値
    "トライセプスプッシュダウン": 10.86 // トライセプス実測値
};

// 種目タイプごとのデフォルト値
const defaultsByJointType = {
    "single": {
        baselineRate: 8.0,
        lbmMetabolicRate: 22,
        fatMetabolicRate: 4.5,
        epocBaseRate: 0.06,
        epocIntensityFactor: 0.12,
        intervalMultiplier: 1.2,
        concentricWeight: 1.0,
        eccentricWeight: 0.4,
        isometricWeight: 0.8
    },
    "multi_upper": {
        baselineRate: 12.0,
        lbmMetabolicRate: 22,
        fatMetabolicRate: 4.5,
        epocBaseRate: 0.06,
        epocIntensityFactor: 0.15,
        intervalMultiplier: 1.3,
        concentricWeight: 1.0,
        eccentricWeight: 0.4,
        isometricWeight: 0.8
    },
    "multi_lower": {
        baselineRate: 25.0,
        lbmMetabolicRate: 22,
        fatMetabolicRate: 4.5,
        epocBaseRate: 0.06,
        epocIntensityFactor: 0.18,
        intervalMultiplier: 1.4,
        concentricWeight: 1.0,
        eccentricWeight: 0.4,
        isometricWeight: 0.8
    },
    "full_body": {
        baselineRate: 30.0,
        lbmMetabolicRate: 22,
        fatMetabolicRate: 4.5,
        epocBaseRate: 0.06,
        epocIntensityFactor: 0.20,
        intervalMultiplier: 1.5,
        concentricWeight: 1.0,
        eccentricWeight: 0.4,
        isometricWeight: 0.8
    },
    "aerobic": {
        baselineRate: null,
        lbmMetabolicRate: null,
        fatMetabolicRate: null,
        epocBaseRate: null,
        epocIntensityFactor: null,
        intervalMultiplier: null,
        concentricWeight: null,
        eccentricWeight: null,
        isometricWeight: null
    }
};

// 全種目にPG式 v2.0デフォルト値を補完
Object.keys(trainingDatabase).forEach(category => {
    Object.keys(trainingDatabase[category]).forEach(exerciseName => {
        const exercise = trainingDatabase[category][exerciseName];

        // 有酸素運動はスキップ
        if (exercise.exerciseType === 'aerobic') {
            return;
        }

        // jointTypeに基づくデフォルト値を取得
        const defaults = defaultsByJointType[exercise.jointType] || defaultsByJointType["single"];

        // baselineRateの設定（実測値があればそれを使用、なければデフォルト）
        if (!exercise.baselineRate) {
            exercise.baselineRate = baselineRateMapping[exerciseName] || defaults.baselineRate;
        }

        // その他の係数も未設定なら補完
        if (!exercise.lbmMetabolicRate) exercise.lbmMetabolicRate = defaults.lbmMetabolicRate;
        if (!exercise.fatMetabolicRate) exercise.fatMetabolicRate = defaults.fatMetabolicRate;
        if (!exercise.epocBaseRate) exercise.epocBaseRate = defaults.epocBaseRate;
        if (!exercise.epocIntensityFactor) exercise.epocIntensityFactor = defaults.epocIntensityFactor;
        if (!exercise.intervalMultiplier) exercise.intervalMultiplier = defaults.intervalMultiplier;
        if (!exercise.concentricWeight) exercise.concentricWeight = defaults.concentricWeight;
        if (!exercise.eccentricWeight) exercise.eccentricWeight = defaults.eccentricWeight;
        if (!exercise.isometricWeight) exercise.isometricWeight = defaults.isometricWeight;
    });
});
